# Generated by Django 2.0.1 on 2018-02-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180207_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatar.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[('0', 'Student'), ('1', 'Teacher'), ('2', 'Admin')], default='0'),
        ),
    ]
