# Generated by Django 2.0.1 on 2018-02-07 05:15

from django.db import migrations, models
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='version',
            field=ool.VersionField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[('0', 'student'), ('1', 'teacher'), ('2', 'admin')], default='0'),
        ),
    ]
