# Generated by Django 2.0.1 on 2018-02-07 14:58

from django.db import migrations
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180207_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=users.models._upload_location),
        ),
    ]
